lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 3600

  token_extractors:
    authorization_header:
      enabled: true
      prefix: Bearer
      name: Authorization

    cookie:
      enabled: true
      name: jwt-token-ticket

  set_cookies:
    jwt-token-ticket:
      path: /
      httpOnly: true
      samesite: none
      secure: false

  remove_token_from_body_when_cookies_used: false

  blocklist_token:
    enabled: true
    cache: cache.app
