nelmio_cors:
    defaults:
        allow_origin:
            - 'http://localhost:3000'
        allow_credentials: true
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        max_age: 3600
